### ISSUE TITLE
Any way to configure pipeline*.yml or task*.yml to be a concourse grammer

### ISSUE THREAD

**Issue by EugenMayer** [spring-projects/atom-concourse#2]
we mostly have something like pipeline_release.yml and pipeline_staging.yml - would it possible to define a glob for auto-matching the files to be opened a pipeline / task grammar supported? Thanks

**Comment by BoykoAlex** [comment]
That was the initial plan. It is done in VSCode. However, Atom doesn't allow glob pattern for files to be opened with a particular grammar... only file extensions or full file names work. There is a `file-types` extension that would allow one to associate more file types with a specific grammar in Atom `config.cson`. Try this as a workaround. Meanwhile we'll check if we can set something like it with our Atom package

**Comment by EugenMayer** [comment]
thank you! switched to visual . studio code in the meantime.. pity the outline is missing there

**Comment by BoykoAlex** [comment]
Instead of the outline view you could try `Go to Symbol in File` - it's the same thing really. It'd show the outline if nothing is typed in.
There is something new in Atom core for grammar file association: `customFileTypes` settings - I can explore it a bit. Maybe lt'll help.
We can also just add `pipeline_release.yml` and `pipeline_staging.yml` for now for the Atom extension to make it more usable for you :-) I wouldn't want you to move from Atom to VSCode just for this little missing piece :-)
We're releasing start of next week and can get this little workaround in.

**Comment by EugenMayer** [comment]
@BoykoAlex thank you for your effort!

I moved to VS code because of a couple more reasons, including far better intellij keybindings and darcula support, but also performance of the IDE and workspaces. I am using the symbol lookup, but well, its not really the same since you do not have a visual, hierachical strucutre

**Comment by EugenMayer** [comment]
@BoykoAlex any way to create issues for councourse for visual studio code for you? https://marketplace.visualstudio.com/items?itemName=patrys.vscode-code-outline could be used for the outline

**Comment by BoykoAlex** [comment]
This the Atom release repo. The source code repo is https://github.com/spring-projects/sts4/issues You can create issues there for VSCode.

**Comment by BoykoAlex** [comment]
I think this needs to be closed
