### ISSUE TITLE
Publish Latest version

### ISSUE THREAD

**Issue by maxknee** [spring-projects/atom-concourse#9]
Are you able to release the latest version to download via APM?

**Comment by BoykoAlex** [comment]
Atom isn't supported anymore as its language client does not seem to be supported anymore. You could install the extension from git using these instructions: https://github.com/spring-projects/atom-concourse#releases (hope it all still works)
Otherwise supported IDEs are  VSCode, Theia, Eclipse with the same concourse extension

**Comment by maxknee** [comment]
ah, gotcha thanks
